server:
  port: 8880
  max-http-header-size: 64KB
  error:
    include-message: always
spring:
  application:
    name: jetlinks-docs
  codec:
    max-in-memory-size: 10MB
jetlinks:
  docs:
    github:
      webhook-token: jetlinks
      api-token: jetlinks
      api-version: 2022-11-28
    param:
      startTime: 2022-11-28 00:00:00
      mode: scope
    yuque:
      id: 136495415
      token: yuque
      title: test
      slug: ms0omgvm77oyb55q
      format: markdown
      force_asl: true